status = error

rootLogger.level = WARN

rootLogger.appenderRef.console.ref = console

appender.console.type = Console
appender.console.name = console
appender.console.target = SYSTEM_OUT

appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{HH:mm:ss} %-5p %c - %m%n

logger.spark.name = org.apache.spark
logger.spark.level = WARN

logger.jetty.name = org.sparkproject.jetty
logger.jetty.level = ERROR

logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = ERROR

logger.kafka.name = org.apache.kafka
logger.kafka.level = ERROR

logger.netty.name = io.netty
logger.netty.level = ERROR