services:
  spark:
    build:
      context: .
      dockerfile: docker/spark/Dockerfile

    container_name: retail-spark

    environment:
      PYTHONPATH: /app/src
#      GCODE
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092

    volumes:
      - ./src:/app/src
      - ./datasets:/app/datasets
      - ./data:/app/data
      - ./checkpoints:/app/checkpoints

    working_dir: /app

    tty: true

    depends_on:
      - kafka



    networks:
      - realtime-platform

  kafka:
    image: confluentinc/cp-kafka:7.7.1
    container_name: kafka
    hostname: kafka

    env_file:
      - docker/kafka/kafka.env

#G

    environment:

      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

    ports:
#      - "${HOST_KAFKA_PORT}:9092"
      - "9092:9092"

    volumes:
      - ${KAFKA_VOLUME}:/var/lib/kafka/data

    restart: unless-stopped

    networks:
      - realtime-platform
volumes:
  kafka-data:

networks:
  realtime-platform:
#    name: ${NETWORK_NAME}
    driver: bridge