[pytest]

python_files = test_*.py

python_classes = Test*

python_functions = test_*

testpaths =
    tests

pythonpath =
    src

addopts =
    -ra
    --strict-markers
    --tb=short

markers =
    unit: Unit Tests
    integration: Integration Tests
    spark: Spark Tests
    kafka: Kafka Tests
    delta: Delta Tests